# Default labels
- name: "breaking change"
  color: "b60205"

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "dependencies"
  color: "1d76db"
  description: "Pull requests that update a dependency file"

- name: "DO NOT MERGE"
  color: "b60205"

- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "fe9b9c"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "ignore for release"
  color: "bfd4f2"
  description: "Exclude from Release Notes"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "work in progress"
  color: "e5d19e"

# Type labels
- name: "type:feature"
  color: "ededed"
  description: "A new feature"
  from_name: "type/feature"

- name: "type:fix"
  color: "ededed"
  description: "A bug fix"
  from_name: "type/fix"

- name: "type:docs"
  color: "ededed"
  description: "Documentation only changes"
  from_name: "type/docs"

- name: "type:style"
  color: "ededed"
  description: "Changes that do not affect the meaning of the code"
  from_name: "type/style"

- name: "type:refactor"
  color: "ededed"
  description: "A code change that neither fixes a bug nor adds a feature"
  from_name: "type/refactor"

- name: "type:perf"
  color: "ededed"
  description: "A code change that improves performance"
  from_name: "type/perf"

- name: "type:test"
  color: "ededed"
  description: "Adding missing tests or correcting existing tests"
  from_name: "type/test"

- name: "type:build"
  color: "ededed"
  description: "Changes that affect the build system or external dependencies"
  from_name: "type/build"

- name: "type:ci"
  color: "ededed"
  description: "Changes to our CI configuration files and scripts"
  from_name: "type/ci"

- name: "type:chore"
  color: "ededed"
  description: "Other changes that don't modify src or test files"
  from_name: "type/chore"

- name: "type:revert"
  color: "ededed"
  description: "Reverts a previous commit"
  from_name: "type/revert"
