name: "Assign author to Pull request"

on:
  pull_request:
    types: [ opened ]

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-24.04-arm
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Assign Author
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
