name: Deploy to Cloudflare Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-24.04-arm
    environment: production
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy
        uses: ./.github/actions/build-deploy
        with:
          project-name: vectacojp
          branch: ${{ vars.PAGES_BRANCH }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
