name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - .github/release-please-manifest.json

concurrency:
  group:  ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Get new version
        id: resolve-versions
        uses: ./.github/actions/resolve-versions
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Create release
        id: create-release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          result-encoding: string
          script: |
            const releaseVersion = '${{ steps.resolve-versions.outputs.current-version }}';
            const release = await github.rest.repos.createRelease({
              ...context.repo,
              tag_name: `v${releaseVersion}`,
              generate_release_notes: true,
            });

            return release.data.html_url;

      - name: Comment on PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const releaseHtmlUrl = '${{ steps.create-release.outputs.result }}';
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.number,
              body: `:robot: Release is at ${releaseHtmlUrl} :sunflower:`
            });
