name: Slash Command

on:
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}-${{ github.event.comment.id }}
  cancel-in-progress: true

jobs:
  ########################################
  # Common
  ########################################
  pull-request:
    name: Get Pull Request Info
    runs-on: ubuntu-24.04-arm
    if: github.event.issue.pull_request
    outputs:
      ref: ${{ steps.pull-request.outputs.ref }}
      number: ${{ steps.pull-request.outputs.number }}
      title: ${{ steps.pull-request.outputs.title }}
      body: ${{ steps.pull-request.outputs.body }}
      head-ref: ${{ steps.pull-request.outputs.head-ref }}
      base-ref: ${{ steps.pull-request.outputs.base-ref }}
      head-sha: ${{ steps.pull-request.outputs.head-sha }}
      url: ${{ steps.pull-request.outputs.url }}
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Get Pull Request details
        id: pull-request
        run: |
          pull_request=$(gh pr view "${{ github.event.issue.number }}" --repo "${{ github.repository }}" --json number,title,body,headRefName,baseRefName,headRefOid,url)

          # outputs
          {
            echo ref="$(jq -r .headRefName <<<"$pull_request")"
            echo number="$(jq -r .number <<<"$pull_request")"
            echo title="$(jq -r .title <<<"$pull_request")"
            echo head-ref="$(jq -r .headRefName <<<"$pull_request")"
            echo base-ref="$(jq -r .baseRefName <<<"$pull_request")"
            echo head-sha="$(jq -r .headRefOid <<<"$pull_request")"
            echo url="$(jq -r .url <<<"$pull_request")"
            echo 'body<<EOF'
            jq -r .body <<<"$pull_request"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

          # display
          echo "::group::Pull Request Info"
          echo "${pull_request}"
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  ########################################
  # Preview
  ########################################
  preview-command:
    name: Preview Command
    runs-on: ubuntu-24.04-arm
    if: github.event.issue.pull_request
    outputs:
      continue: ${{ steps.preview-command.outputs.continue }}
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/command-action
      - name: Preview Command
        id: preview-command
        uses: github/command@3ef62aea1e21fa68d85e57df4fd0edcca5cc4b53 # v2.0.1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          command: /preview
          reaction: "eyes"
          allowed_contexts: "pull_request"
          skip_ci: "true"
          skip_reviews: "true"

  preview:
    needs:
      - pull-request
      - preview-command
    if: ${{ needs.preview-command.outputs.continue == 'true' }}
    name: Preview
    uses: ./.github/workflows/preview.yml
    with:
      gh-app-id: ${{ vars.BOT_APP_ID }}
      ref: ${{ needs.pull-request.outputs.ref }}
      head-sha: ${{ needs.pull-request.outputs.head-sha }}
      sha: ${{ github.sha }}
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
