name: Generate Release Note Body
description: リリースノート本文を生成

inputs:
  version:
    description: v無しバージョン
    required: true
  github-token:
    description: GitHub トークン
    required: false
    default: ${{ github.token }}

outputs:
  body:
    description: 生成されたリリースノート本文'
    value: ${{ steps.generate.outputs.result }}

runs:
  using: composite
  steps:
    - name: Generate release note body
      id: generate
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{ inputs.github-token }}
        result-encoding: string
        script: |
          const { data: { body } } = await github.rest.repos.generateReleaseNotes({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${{ inputs.version }}`,
          });
          return body;

    - name: Set output
      run: |
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "${{ steps.generate.outputs.result }}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash
